In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
#import libraries and some constants

import os
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize, LogNorm
import pandas as pd
import uproot as ur
import atlas_mpl_style as ampl
ampl.use_atlas_style()
import tensorflow as tf

path_prefix = '/g/g16/heinz6/workspace/projects/caloml-atlas/code/caloml-atlas-py/'
plotpath = path_prefix+'regression/Plots/'
modelpath = path_prefix+'regression/Models/'

In [3]:
inputpath = '/g/g16/heinz6/workspace/projects/caloml-atlas/code/atlasml-karande-heinz/'+\
            'store/20200618_piplus_log_mae_dense_allClust_rebin/results/'
fold = '2'

a1 = np.load(inputpath+'inference_piplus_v6_root/inference_data_piplus_log_mae_with_fold_'+fold+'_best.npz')
a2 = np.load(inputpath+'inference_piplus_v6_root/inference_data_piplus_log_mae_with_fold_'+fold+'_best_2.npz')
a3 = np.load(inputpath+'inference_piplus_v6/inference_data_from_train_piplus_log_mae_with_fold_'+fold+'_best.npz')

num_cluster1 = len(a1['calib_pred'])
num_cluster2 = len(a2['calib_pred'])
num_cluster3 = len(a3['calib_pred'])

In [4]:
b1 = a1['calib_pred'][np.arange(num_cluster3)]-a3['calib_pred']

In [5]:
sum(b1==0)

347376

In [6]:
num_cluster3

347376

In [7]:
b2 = a1['calib_pred'][np.arange(num_cluster2)]-a2['calib_pred']

In [8]:
sum(abs(b2/a2['calib_pred']) < 6*10**(-6))

346112

In [9]:
num_cluster2

346112

In [10]:
inputpath2 = '/g/g16/heinz6/workspace/projects/caloml-atlas/code/atlasml-karande-heinz/store/20200721_classifier_crossentropy_dense_allClust_rebin/'

c1 = np.load(inputpath2+'training_data_log_categorical_crossentropy.npz')

In [11]:
label_fold = c1['label_fold']

In [12]:
label_fold.shape

(980274,)

In [13]:
fold = 4
test_inds = np.argwhere(label_fold == fold).reshape(-1)
print(test_inds)

[     5      6      8 ... 980265 980271 980272]


In [14]:
label_pred = c1['label_pred'][test_inds]
print(label_pred.shape)
label_categ = c1['label_categ'][test_inds]
print(label_categ.shape)

(196054, 2)
(196054, 2)


In [15]:
sum(label_pred >0)

array([196050, 196054])

In [16]:
len(test_inds)

196054

In [17]:
m = tf.keras.metrics.CategoricalAccuracy()
_ = m.update_state(label_pred, label_categ)
m.result().numpy()

0.945311

In [18]:
import pickle

In [19]:
with open(inputpath2+'train_hist_log_categorical_crossentropy_4', 'rb') as f:
    x = pickle.load(f)

In [20]:
print(x['loss'])

[0.18019838873419058, 0.15385751019007926, 0.14710538516377883, 0.14279251642517027, 0.1396360442548544, 0.1375042463185905, 0.135138400402045, 0.13339643780015614, 0.13161971219559865, 0.13006248046832358, 0.1285874081586436, 0.1271777904795079, 0.1256923961757136, 0.12476126338183258, 0.12339924931030631, 0.1222098690188228, 0.12117200055123074, 0.11996229539015953, 0.11891487340601092, 0.11790470422585043, 0.11736843746817409, 0.11593329954814206, 0.11526920983515059, 0.11513211203878279, 0.11363956438978556, 0.11255515745343206, 0.1121312830926739, 0.1120356728874434, 0.11038219093290644, 0.10999364029489854, 0.10909636992810014, 0.10819049174100627, 0.1081210694661593, 0.10699580128523341, 0.10627442941406685, 0.106202337808531, 0.10544313881915358, 0.10474019547959694, 0.10429327034716313, 0.10372828345565575, 0.10305995598653156, 0.10308814757785477, 0.10237439525874235, 0.10176631467637914, 0.10083568958145048, 0.1003859761092734, 0.099775667595077, 0.0997495690606209, 0.099133

In [21]:
print(x['val_categorical_accuracy'])

[0.9383180141448975, 0.9401746392250061, 0.9420924782752991, 0.9426790475845337, 0.9414396286010742, 0.9437859058380127, 0.9442449808120728, 0.9445204138755798, 0.9443469643592834, 0.9439899325370789, 0.9448111057281494, 0.9438266754150391, 0.9448315501213074, 0.9447652101516724, 0.9446938037872314, 0.9453110098838806, 0.9449641704559326, 0.9449131488800049, 0.9452242851257324, 0.9449335336685181, 0.9444847106933594, 0.9442398548126221, 0.9446223974227905, 0.9443061351776123, 0.9440001249313354, 0.9444795846939087, 0.9438675045967102, 0.94380122423172, 0.943780779838562, 0.9434543251991272, 0.9438164830207825, 0.9436073899269104, 0.9436940550804138, 0.9434594511985779, 0.9434900879859924, 0.9434441328048706, 0.9430922269821167, 0.9426433444023132, 0.9424648284912109, 0.9428830742835999, 0.9419547915458679, 0.9426994323730469, 0.9426025748252869, 0.9428626894950867, 0.9427555799484253, 0.9424801468849182, 0.9421588182449341, 0.9422608017921448, 0.9416385293006897, 0.9423322081565857, 0.

In [3]:
inputpath3 = '/g/g16/heinz6/workspace/projects/caloml-atlas/code/atlasml-karande-heinz/store/20200724_piplus_log_mae_dense_allEnergy_allClust_rebin/'

piplus = np.load(inputpath3+'training_data_piplus_log_mae.npz')

In [4]:
calib_fold = piplus['calib_fold']

print(calib_fold.shape)

(4073706,)


In [34]:
fold = 4
test_inds = np.argwhere(calib_fold == fold).reshape(-1)
print(test_inds)

calib_pred = piplus['calib_pred']
print(calib_pred.shape)
calib = piplus['calib']
print(calib.shape)

[      0       9      11 ... 4073701 4073702 4073705]
(4073706,)
(4073706,)


In [35]:
calib_ratio = calib_pred/calib

print(np.median(calib_ratio))

0.9946037761676068


In [19]:
import sys
sys.path.append('/g/g16/heinz6/workspace/projects/caloml-atlas/code/atlasml-karande-heinz/')
from helpers import data_processing as dp
from helpers import rebin
from helpers import normalize

model_min_max = np.load(inputpath3+'/calib_min_max_piplus_log.npz')

model_min = model_min_max['calib_min']
model_max = model_min_max['calib_max']

norm_log_calib_pred = normalize.norm(np.log10(calib_pred),xmax=model_max, xmin=model_min)
norm_log_calib = normalize.norm(np.log10(calib),xmax=model_max, xmin=model_min)

#m = tf.keras.losses.MAE(norm_log_calib_pred,norm_log_calib)
#print(m)

Using TensorFlow backend.


In [68]:
import pickle

with open(inputpath3+'train_hist_piplus_log_mae_'+str(fold), 'rb') as f:
    x = pickle.load(f)

print(min(x['loss']))

0.011922924754345003


In [31]:
x['val_loss'][99]

0.012677421647156564

In [80]:
import pickle
inputpath4 = '/g/g16/heinz6/workspace/projects/caloml-atlas/code/atlasml-karande-heinz/store/20200724_piplus_log_mae_dense_allEnergy_allClust_rebin/training_timing/'

batch_size_list = [32,64,128,256,512,1024,2048]
history_dict = {}

for batch_size in batch_size_list:
    with open(inputpath4+'train_hist_piplus_log_mae_'+str(batch_size)+'_1', 'rb') as f:
        history_dict[batch_size] = pickle.load(f)

In [81]:
for batch_size in history_dict:
    print('Minimum validation loss for batch size {}: {}'.format(batch_size, history_dict[batch_size]['val_mse']))

Minimum validation loss for batch size 32: [0.0004050895804539323, 0.0004182677366770804, 0.00041056182817555964, 0.0004155725473538041, 0.00040870727389119565, 0.00040788098704069853, 0.000402767735067755, 0.00041387861710973084, 0.0004057107726112008, 0.000405782280722633]
Minimum validation loss for batch size 64: [0.00040884915506467223, 0.0004086808767169714, 0.00042552503873594105, 0.0004176466027274728, 0.00040606214315630496, 0.0004083111707586795, 0.0004003854701295495, 0.00040995937888510525, 0.00041810577386058867, 0.0003980431647505611]
Minimum validation loss for batch size 128: [0.00041210808558389544, 0.00040056160651147366, 0.0003955659340135753, 0.0004078191705048084, 0.00039917268441058695, 0.00039193424163386226, 0.00039370940066874027, 0.00039360704249702394, 0.00040080081089399755, 0.00039045271114446223]
Minimum validation loss for batch size 256: [0.00041292537935078144, 0.00041718510328792036, 0.00040408989298157394, 0.0003992156416643411, 0.00039428399759344757

In [8]:
a = [0,1,5]

if 5 in a:
    print('lol')

lol
