In [1]:
#import libraries and some constants

import os
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize, LogNorm
import pandas as pd
import uproot as ur
import atlas_mpl_style as ampl
ampl.use_atlas_style()
import tensorflow as tf

import sys
sys.path.append('/g/g16/heinz6/workspace/projects/caloml-atlas/code/atlasml-karande-heinz/')
from util import root_preprocess_util as rpu
from helpers import rebin

Using TensorFlow backend.


In [2]:
inputpath = '/usr/WS1/hip/ML4Jets/regression_images/images_v6_v01-17-g2679fe7/'

tree1 = ur.open(inputpath+'piplus_unscaled_filtered.root')['ClusterTree']
tree2 = ur.open(inputpath+'piplus_fully_processed.root')['ClusterTree']

In [3]:
tree1.keys()

[b'runNumber',
 b'eventNumber',
 b'truthE',
 b'truthPt',
 b'truthEta',
 b'truthPhi',
 b'clusterIndex',
 b'clusterE',
 b'clusterECalib',
 b'clusterPt',
 b'clusterEta',
 b'clusterPhi',
 b'cluster_nCells',
 b'cluster_sumCellE',
 b'cluster_ENG_CALIB_TOT',
 b'cluster_ENG_CALIB_OUT_T',
 b'cluster_ENG_CALIB_DEAD_TOT',
 b'cluster_EM_PROBABILITY',
 b'cluster_HAD_WEIGHT',
 b'cluster_OOC_WEIGHT',
 b'cluster_DM_WEIGHT',
 b'cluster_CENTER_MAG',
 b'cluster_FIRST_ENG_DENS',
 b'cluster_cell_dR_min',
 b'cluster_cell_dR_max',
 b'cluster_cell_dEta_min',
 b'cluster_cell_dEta_max',
 b'cluster_cell_dPhi_min',
 b'cluster_cell_dPhi_max',
 b'cluster_cell_centerCellEta',
 b'cluster_cell_centerCellPhi',
 b'cluster_cell_centerCellLayer',
 b'cluster_cellE_norm',
 b'duplicate_EMB1',
 b'duplicate_EMB2',
 b'duplicate_EMB3',
 b'duplicate_TileBar0',
 b'duplicate_TileBar1',
 b'duplicate_TileBar2',
 b'EMB1',
 b'EMB2',
 b'EMB3',
 b'TileBar0',
 b'TileBar1',
 b'TileBar2']

In [4]:
tree2.keys()

[b'runNumber',
 b'eventNumber',
 b'truthE',
 b'truthPt',
 b'truthEta',
 b'truthPhi',
 b'clusterIndex',
 b'clusterE',
 b'clusterECalib',
 b'clusterPt',
 b'clusterEta',
 b'clusterPhi',
 b'cluster_nCells',
 b'cluster_sumCellE',
 b'cluster_ENG_CALIB_TOT',
 b'cluster_ENG_CALIB_OUT_T',
 b'cluster_ENG_CALIB_DEAD_TOT',
 b'cluster_EM_PROBABILITY',
 b'cluster_HAD_WEIGHT',
 b'cluster_OOC_WEIGHT',
 b'cluster_DM_WEIGHT',
 b'cluster_CENTER_MAG',
 b'cluster_FIRST_ENG_DENS',
 b'cluster_cell_dR_min',
 b'cluster_cell_dR_max',
 b'cluster_cell_dEta_min',
 b'cluster_cell_dEta_max',
 b'cluster_cell_dPhi_min',
 b'cluster_cell_dPhi_max',
 b'cluster_cell_centerCellEta',
 b'cluster_cell_centerCellPhi',
 b'cluster_cell_centerCellLayer',
 b'cluster_cellE_norm',
 b'duplicate_EMB1',
 b'duplicate_EMB2',
 b'duplicate_EMB3',
 b'duplicate_TileBar0',
 b'duplicate_TileBar1',
 b'duplicate_TileBar2',
 b'EMB1',
 b'EMB2',
 b'EMB3',
 b'TileBar0',
 b'TileBar1',
 b'TileBar2',
 b'Tiles',
 b'EMB1_expand',
 b'EMB23']

In [5]:
emb2_diff = tree1.array('EMB2') - tree2.array('EMB2')
print(len(emb2_diff), sum(sum(emb2_diff==0)==len(emb2_diff)))

347377 [16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]


In [6]:
emb3_diff = tree1.array('EMB3') - tree2.array('EMB3')
print(len(emb3_diff), sum(sum(emb3_diff==0)==len(emb3_diff)))

347377 [8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]


In [7]:
emb2 = tree1.array('EMB2')
emb3 = tree1.array('EMB3')

emb3 = rebin.rebinUpCluster(emb3, 16, 16)

emb23 = np.stack([emb2, emb3], axis=3)

emb23_diff = emb23 - tree2.array('EMB23')

In [9]:
print(len(emb23_diff), sum(sum(emb23_diff==0)==len(emb23_diff)))

347377 [[16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]
 [16 16]]


In [12]:
emb1 = tree1.array('EMB1')

emb1 = np.expand_dims(emb1,axis=3)

emb1_diff = emb1 - tree2.array('EMB1_expand')

In [13]:
print(len(emb1_diff), sum(sum(emb1_diff==0)==len(emb1_diff)))

347377 [[128]
 [128]
 [128]
 [128]]


In [14]:
tile0 = tree1.array('TileBar0')
tile1 = tree1.array('TileBar1')
tile2 = tree1.array('TileBar2')

tile2 = rebin.rebinUpCluster(tile2, 4, 4)

tiles = np.stack([tile0, tile1, tile2], axis=3)

tiles_diff = tiles - tree2.array('Tiles')

In [15]:
print(len(tiles_diff), sum(sum(tiles_diff==0)==len(tiles_diff)))

347377 [[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]
